# Site settings
title: "Personal Workspace"
description: "A showcase of my projects and achievements"
url: "https://github.com/gabriele9123"
baseurl: "/personal_workspace"  # Leave empty if deploying to root
author: "Gabriele Pascaretta"

# GitHub Pages settings
repository: gabriele9123/personal_workspace

# Theme settings
theme: minima 

# Social media
github_username: gabriele9123
linkedin_username: gabriele-pascaretta
